The Micronaut framework supports sending files to the client in a couple of easy ways.

== Sending File Objects

It is possible to return a link:{jdkapi}/java.base/java/io/File.html[File] object from your controller method, and the data will be returned to the client. The `Content-Type` header of file responses is calculated based on the name of the file.

To control either the media type of the file being sent, or to set the file to be downloaded (i.e. using the `Content-Disposition` header), instead construct a api:http.server.types.files.SystemFile[] with the file to use. For example:

.Sending a SystemFile
[source,java]
----
@Get
public SystemFile download() {
    File file = ...
    return new SystemFile(file).attach("myfile.txt");
    // or new SystemFile(file, MediaType.TEXT_HTML_TYPE)
}
----

== Sending an InputStream

For cases where a reference to a `File` object is not possible (for example resources in JAR files), the Micronaut framework supports transferring input streams. To return a stream of data from the controller method, construct a api:http.server.types.files.StreamedFile[].

TIP: The constructor for `StreamedFile` also accepts a `java.net.URL` for your convenience.

.Sending a StreamedFile
[source,java]
----
@Get
public StreamedFile download() {
    InputStream inputStream = ...
    return new StreamedFile(inputStream, MediaType.TEXT_PLAIN_TYPE)
    // An attach(String filename) method is also available to set the Content-Disposition
}
----

The server supports returning `304` (Not Modified) responses if the files being transferred have not changed, and the request contains the appropriate header. In addition, if the client accepts encoded responses, the Micronaut framework encodes the file if appropriate. Encoding happens if the file is text-based and larger than 1KB by default. The threshold at which data is encoded is configurable. See the server configuration reference for details.

TIP: To use a custom data source to send data through an input stream, construct a link:{jdkapi}/java.base/java/io/PipedInputStream.html[PipedInputStream] and link:{jdkapi}/java.base/java/io/PipedOutputStream.html[PipedOutputStream] to write data from the output stream to the input. Make sure to do the work on a separate thread so the file can be returned immediately.

== Sending Reactive Streams as File Downloads
Micronaut also supports returning *reactive streams* (e.g., `Flux`, `Flowable`,
or any `Publisher`) without buffering the entire response in memory. If you want to
force the client browser to download the streamed data (for example, CSV lines),
you can set the `Content-Disposition: attachment` header.

snippet::io.micronaut.docs.server.transfer.DownloadController[tags="class,endclass", indent=0, title="Sending Reactive Stream"]

NOTE: Wrapping your stream in `HttpResponse<Flux<String>>` does not cause
the entire CSV to be loaded into memory. Micronaut will still *stream*
the data as it is produced. Returning `HttpResponse<T>` simply allows you
to set any headers or custom status codes.

== Cache Configuration

By default, file responses include caching headers. The following options determine how the `Cache-Control` header is built.

include::{includedir}configurationProperties/io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$FileTypeHandlerConfiguration.adoc[]

include::{includedir}configurationProperties/io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$FileTypeHandlerConfiguration$CacheControlConfiguration.adoc[]
